### ISSUE TITLE
introduce loop task

### ISSUE THREAD

**Issue by johnnychen94** [johnnychen94/Workflows.jl#10]
- a workflow consists of a mixture of `[[loops]]` and `[[tasks]]`
- a loop consists of one `[matrix]` definition and multiple `[[tasks]]` definitions
- a loop also has an `id` for reference purpose

```toml
[[loops]]
id = "1"
[loops.matrix]
script = ["rand.jl", "sum.jl"]
length = ["64", "128", "256", "512", "1024", "2048", "4096"]
[[loops.matrix.includes]]
script = "sum.jl"
length = "8192"
[[loops.matrix.excludes]]
script = "rand.jl"
length = "4096"
[[loops.tasks]]
name = "basic"
id = "basic__julia__{{ matrix.index }}"
groups = ["Type:LinearAlgebra", "Type:Benchmark", "Framework:Julia"]
runner = "shell"
[loops.tasks.run]
command = "julia --startup=no --project=. {{ matrix.script }} {{ matrix.length }} "

[[loops]]
id = "2"
[loops.matrix]
script = ["rand.py", "sum.py"]
length = ["64", "128", "256", "512", "1024", "2048"]
[[loops.tasks]]
name = "basic"
id = "basic__numpy__{{ matrix.index }}"
groups = ["Type:LinearAlgebra", "Type:Benchmark", "Framework:Numpy"]
runner = "shell"
[loops.tasks.run]
command = "python {{ matrix.script }} {{ matrix.length }} "

[[tasks]]
name = "summary"
id = "3"
groups = ["Type:LinearAlgebra", "Type:Benchmark"]
deps = [
    "summary.jl",
    "@__STDOUT__1",
    "@__STDOUT__2",
]
outs = ["reports"]
runner = "shell"
[tasks.run]
command = "julia --startup=no --project=. summary.jl"
```
