### ISSUE TITLE
introduce YAML format

### ISSUE THREAD

**Issue by johnnychen94** [johnnychen94/Workflows.jl#11]
It's perhaps a matter of taste here, TOML can become less readable than YAML when there exists a deeply nested structure. For instance, the following is the TOML version of our UnitTest.yml file without indentation:

```toml
name = "CI"

[jobs.test]
runs-on = "${{ matrix.os }}"

[[jobs.test.steps]]
uses = "actions/checkout@v2"
[[jobs.test.steps]]
name = "Set up Julia"
uses = "julia-actions/setup-julia@v1"

[jobs.test.steps.with]
arch = "${{ matrix.arch }}"
version = "${{ matrix.julia-version }}"
[[jobs.test.steps]]
name = "Cache artifacts"
uses = "actions/cache@v1"

[jobs.test.steps.env]
cache-name = "cache-artifacts"

[jobs.test.steps.with]
key = "${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}"
path = "~/.julia/artifacts"
restore-keys = "${{ runner.os }}-test-${{ env.cache-name }}-\n${{ runner.os }}-test-\n${{ runner.os }}-\n"
[[jobs.test.steps]]
name = "Unit Test"
uses = "julia-actions/julia-runtest@master"
[[jobs.test.steps]]
uses = "julia-actions/julia-processcoverage@v1"
[[jobs.test.steps]]
uses = "codecov/codecov-action@v1"

[jobs.test.steps.with]
file = "lcov.info"

[jobs.test.strategy]
fail-fast = false

[jobs.test.strategy.matrix]
arch = ["x64"]
julia-version = ["1.6", "1", "nightly"]
os = ["ubuntu-latest"]

[[jobs.test.strategy.matrix.include]]
arch = "x64"
julia-version = "1"
os = "windows-latest"
[[jobs.test.strategy.matrix.include]]
arch = "x64"
julia-version = "1"
os = "macOS-latest"
```

Given that TOML is shipped as Julia's stdlib, we might still want to use it as the default internal representation.
