### ISSUE TITLE
pass arguments to juliamodule runner

### ISSUE THREAD

**Issue by johnnychen94** [johnnychen94/Workflows.jl#15]
For the shell version:

```toml
[[tasks]]
    name = "task1"
    id = "1"
    runner = "shell"
    [tasks.matrix]
        a = [1, 2, 3, 4, 5]
        b = [2, 4, 6, 8, 10]
    [tasks.run]
        command = "julia main.jl ${{ matrix.a }} ${{ matrix.b }}"
```

Would like to make something like the following work:

```julia
[[tasks]]
    name = "task1"
    id = "1"
    runner = "juliamodule"
    [tasks.matrix]
        a = [1, 2, 3, 4, 5]
        b = [2, 4, 6, 8, 10]
    [tasks.run]
        script = "main.jl"
        args = [${{ matrix.a }}, ${{ matrix.b }}]
```

This might require Julia 1.8: `https://github.com/JuliaLang/julia/pull/44137`
