### ISSUE TITLE
interpolate environment variables

### ISSUE THREAD

**Issue by johnnychen94** [johnnychen94/Workflows.jl#16]
A typical usage could be:

```toml
[[tasks]]
    runner = "shell"
    [tasks.run]
        command = "julia --threads=${{ env.JULIA_NUM_THREADS }} main.jl"
```
