### ISSUE TITLE
include other workflows

### ISSUE THREAD

**Issue by johnnychen94** [johnnychen94/Workflows.jl#26]
Something like

```toml
version = "0.2"
dialect = "manifest"
includes = ["./workflow_a.toml", "https://url/to/workflow_b.toml"]
```

- the entire workflow as one single gigantic task, or merge tasks?
- should have a way to detect if the dialect used in the remote file is supported.
