### ISSUE TITLE
support multiple commands in single task

### ISSUE THREAD

**Issue by johnnychen94** [johnnychen94/Workflows.jl#33]
```yml
tasks:
  - name: "task"
    id: "1"
    runner: shell
    command:
      - echo 1
      - echo 2
```
