### ISSUE TITLE
support alias

### ISSUE THREAD

**Issue by johnnychen94** [johnnychen94/Workflows.jl#5]
Somehow I'd like to see

```toml
[[alias]]
name = "versioninfo"
runner = "shell"
[alias.run]
command = "julia --startup=no -e 'using InteractiveUtils; versioninfo()'"

[[tasks]]
name = "check versions"
runner = "versioninfo"
```

and equivalent version of

```toml
[[tasks]]
name = "check versions"
runner = "shell"
[alias.run]
command = "julia --startup=no -e 'using InteractiveUtils; versioninfo()'"
```
