### ISSUE TITLE
shell driver: support pipes

### ISSUE THREAD

**Issue by johnnychen94** [johnnychen94/Workflows.jl#7]
```toml
driver = "shell"
command = "ls -l | wc -l"
```

should be transcripted to the pipeline version

```julia
run(pipeline(pipeline(`ls -l`), `wc -l`))
```
